// lib/features/wakatime_auth/domain/entities/wakatime_scope.dart

enum WakaTimeScope {
  readSummaries,
  readSummariesCategories,
  readSummariesDependencies,
  readSummariesEditors,
  readSummariesLanguages,
  readSummariesMachines,
  readSummariesOperatingSystems,
  readSummariesProjects,
  readStats,
  readStatsBestDay,
  readStatsCategories,
  readStatsDependencies,
  readStatsEditors,
  readStatsLanguages,
  readStatsMachines,
  readStatsOperatingSystems,
  readStatsProjects,
  readGoals,
  readOrgs,
  writeOrgs,
  readPrivateLeaderboards,
  writePrivateLeaderboards,
  readHeartbeats,
  writeHeartbeats,
  email,
}
